### PR TITLE
Made framework and header search paths relative to project. Fixed typo

### PR DESCRIPTION
**Pull request by wanderingstan**
In trying the iOS samples noticed a few small errors. Nice SDK overall!

HelloWorld Framework Search Path had absolute path: 
`/Users/wes/Git/sdk/PUBLIC/Sphero-iOS-SDK/frameworks`
changed to
`$(SRCROOT)/../../frameworks`

`SensorStreaming/ViewController.m` had typo in method name. (Note extra 'l')
`[_robot enableStablilization:NO];`

### CODE REVIEW

**Comment by iamcgn** [comment]
Hi @wanderingstan,
Thanks for the feedback and pull request! Everything looks great except the LED color change in the hello world example. Blinking red indicates a low or critical battery so we try to avoid blinking red (even in sample code :) ). If you wouldn't mind changing that line back and re-submitting I'll be happy to merge this in.

**Comment by wanderingstan** [comment]
Oops, totally forgot that I changed the color when first playing with the
code. I'll change and re-submit!

On Wed, Jan 6, 2016 at 1:34 PM, Corey <notifications@github.com> wrote:

> Hi @wanderingstan <https://github.com/wanderingstan>,
> Thanks for the feedback and pull request! Everything looks great except
> the LED color change in the hello world example. Blinking red indicates a
> low or critical battery so we try to avoid blinking red (even in sample
> code :) ). If you wouldn't mind changing that line back and re-submitting
> I'll be happy to merge this in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orbotix/Sphero-iOS-SDK/pull/41#issuecomment-169470083>
> .
>



-- 
wanderingstan.com / art <http://instagram.com/wanderingstan> / fb
<https://www.facebook.com/wanderingstan> / tw
<http://twitter.com/wanderingstan> / 917-575-2435

**Comment by wanderingstan** [comment]
Ok, I changed LED colors back to match original code (only blinking blue). We should be good to go!

**Comment by iamcgn** [comment]
Thanks!

**Pull request merged**
